version: '3.8'
services:
  backend:
    build: .
    command: uvicorn backend:app --host 0.0.0.0 --port 10000
    ports:
      - "10000:10000"
    environment:
      - ENV=production

  frontend:
    build: .
    command: streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
